services:
  comfyui-worker:
    image: akpro04/worker-comfyui:${RELEASE_VERSION:-latest}-base-cuda12.8.1
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/custom_nodes:/comfyui/custom_nodes
      - ./data/runpod-volume/models:/comfyui/models


## docker buildx bake base-cuda13-1
## RELEASE_VERSION=2.0 docker buildx bake base-cuda12-8-1